name: builder
on:
  push:
    branches:
      - main
  # Uncomment the section below to enable scheduled builds
  schedule:
    # Run this script every 1 hr
    #  */m hr day month day_of_week
    - cron:  '8 * * * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'tag'  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install and Run Node Script
        run: |
          npm ci --omit=dev
          npm run build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          single-commit: true
          branch: gh-pages
          folder: output
